### ISSUE TITLE
Train/Test split

### ISSUE THREAD

**Issue by bald6354** [SensorsINI/DHP19#12]
Thank you for your work in developing this dataset. The paper states, "We split the 17 subjects into 12 subjects for training and validation (9 female, 3 male), and 5 for testing (3 female, 2 male). Can you please provide which subjects were used for testing/training or a label of female/male for each subject? Were they actually just S1-S5 as listed in Table 5 or are those relabeled for the paper? Thanks!

**Comment by enrico-c** [comment]
Hi @bald6354 ,

Here is a table where you can find the train/test split information (as described [here](https://sites.google.com/view/dhp19/user-guide#h.p_yYv-B2REAImG)) and female/male information for each subject.
Table 5 in the paper refers only to the test subjects: in fact, the test subjects are after the training subjects (S13 to S17)

| Subject | Gender | Test subject |
|:--------:|:------:|:-------------:|
|    S1    |    F   |               |
|    S2    |    F   |               |
|    S3    |    F   |               |
|    S4    |    F   |               |
|    S5    |    F   |               |
|    S6    |    M   |               |
|    S7    |    M   |               |
|    S8    |    F   |               |
|    S9    |    F   |               |
|    S10   |    M   |               |
|    S11   |    F   |               |
|    S12   |    F   |               |
|    S13   |    F   |     test 1    |
|    S14   |    M   |     test 2    |
|    S15   |    F   |     test 3    |
|    S16   |    M   |     test 4    |
|    S17   |    F   |     test 5    |

**Comment by bald6354** [comment]
Thank you!
