### ISSUE TITLE
Missing Vicon Data for Subject 14

### ISSUE THREAD

**Issue by bald6354** [SensorsINI/DHP19#13]
The truth vicon data for subject 14/session 4/movements 23-26 appear to be completely missing hipL joint positions. For your paper did you just calculate the MPJPE using the remaining joint locations (ignoring the hipL joint)? This seems fair, but if you could provide clarification I would appreciate it. Thanks again for this great dataset!

**Comment by enrico-c** [comment]
Yes, for samples with missing ground truth joints the error is calculated on the remaining joints

**Comment by bald6354** [comment]
Thanks for the quick reply!
