### ISSUE TITLE
How to download DHP 19 dataset in Linux?

### ISSUE THREAD

**Issue by lyhsieh** [SensorsINI/DHP19#16]
Is there any tutorial related to my problem?
Thanks for your help!

**Comment by enrico-c** [comment]
Hi,
what is exactly the problem you're facing?

Could you install Resilio Sync? 
(If not, there are instructions on their official website, e.g., https://help.resilio.com/hc/en-us/articles/206178924 or https://www.resilio.com/blog/official-linux-packages-for-sync-now-available)

**Comment by tobidelbruck** [comment]
Please google resiliosync linux... or check the ddd20 readme 
https://sites.google.com/view/davis-driving-dataset-2020/home

Sorry about the hassle with download. We hope to migrate some of these 
datasets to simpler cloud storage in future but it is too expensive for 
us now.
