### ISSUE TITLE
Problem reading the .aedat file

### ISSUE THREAD

**Issue by victkid** [SensorsINI/DHP19#2]
Hi, 

I'm running the `Generate_DHP19.m` script to read .aedat file. I got the error message says 
```
Undefined function or variable 'normalizeImage3Sigma'.

Error in ExtractEventsToFramesAndMeanLabels (line 85)
            I1n = uint8(normalizeImage3Sigma(I1s));

Error in Generate_DHP19 (line 288)
                ExtractEventsToFramesAndMeanLabels( ...
```
I tried to search this function within the repo, but couldn't find the function. Looks like the `normalizeImage3Sigma` function is missing from the file. Does anyone know how to solve this issue? Thanks in advance.

**Comment by tobidelbruck** [comment]
Maybe something wasn't pushed?  I have to leave it to Enrico or Gemma to answer this and other issues on DHP19.

**Comment by enrico-c** [comment]
Right, the function was not there, I added it. 
Thank you
