### ISSUE TITLE
"waiting for approval" in Resilio

### ISSUE THREAD

**Issue by takeyamayuki** [SensorsINI/DHP19#21]
Hello. Thank you for your great project.

I have a question. 
In downloading the DHP19 dataset, the status is "waiting for approval" in Resilio.
Do I need approval from SensorsINI? or is there some other correct way to do it?

Thank you in advance.

![image](https://user-images.githubusercontent.com/22733958/194230748-0141a153-0ae9-48b7-ba96-9faf342fa57a.png)

**Comment by takeyamayuki** [comment]
It worked from home, not from the university network.

**Comment by tobidelbruck** [comment]
I think it might continue to work at lab once it is connected outwards.

If that is true then please let us know. Thanks!
