### ISSUE TITLE
May I ask how you are viewing the aedat file? When I view them using AEViewer, the images from the 4 DVS cameras overlap on one screen and I can't see the movements.

### ISSUE THREAD

**Issue by lsjws2008** [SensorsINI/DHP19#24]
![微信图片_20240327153505](https://github.com/SensorsINI/DHP19/assets/25790531/e234ba49-6ada-462b-90d7-b9d1edd0b3f4)

**Comment by tobidelbruck** [comment]
Where did you get the file exactly? I can have a look to see if we can remember how in jAER the data is stored. 

As I recall they are stored as 4 AEDAT files with one .idx file that lists the four files. Then you open the idx file that should open 4 AEViewers that should be synchronized.

**Comment by lsjws2008** [comment]
The image shows the file "DVS_movies\S5\session3\mov1.aedat." I directly opened the file using AEViewer. Is this operation correct?

**Comment by lsjws2008** [comment]
> Where did you get the file exactly? I can have a look to see if we can remember how in jAER the data is stored.
> 
> As I recall they are stored as 4 AEDAT files with one .idx file that lists the four files. Then you open the idx file that should open 4 AEViewers that should be synchronized.

The image shows the file "DVS_movies\S5\session3\mov1.aedat." I directly opened the file using AEViewer. Is this operation correct?

**Comment by tobidelbruck** [comment]
No, you should open the aeidx file, that will open four viewers for the 4 files. That is what I recall. Let me know if that doesn't work.

**Comment by lsjws2008** [comment]
I get what you mean. However, in the files synchronized from Resilio Sync, none of the filenames contain "aeidx".
![微信图片_20240328203457](https://github.com/SensorsINI/DHP19/assets/25790531/1354e383-b820-4976-adac-5cfc2b3dbecd)

**Comment by tobidelbruck** [comment]
hmm, then I'm not sure. You can try to make an .aeidx file.  It just has one file per line. I will give it a try later, am trying to finish overdue report today for one of our projects.

**Comment by tobidelbruck** [comment]
BTW how are the files named, what is the camera index? There should be 4 DVS cameras per session

**Comment by tobidelbruck** [comment]
OK, I finally had a chance to look and I'm sorry to have misinformed you. The correct way to view the recordings in jAER is to use the _AEChip_ `MultiDAVIS346BCameraChip`.   With this _AEChip_, the 2 lsbs of the address are decoded to provide the X address offset. The clue is in the [paper ](https://openaccess.thecvf.com/content_CVPRW_2019/papers/EventVision/Calabrese_DHP19_Dynamic_Vision_Sensor_3D_Human_Pose_Dataset_CVPRW_2019_paper.pdf) where it is stated:

      DVS data format. The dataset contains only DVS data
      from the four DAVIS cameras. We adapted the standard
      DVS data format to the multi-camera setup case. We
      merged the streams of DVS events from each camera to 
      ensure monotonic timestamp ordering, 
      and included the identification (ID) number of each 
      camera in the two least significant bits of the raw address.
       In this way, each event is
      represented by a tuple e = (x, y, t, p, c). Where (x, y) is
      the address in the pixel array, t is the time information in
      microsecond resolution, p is the polarity of the brightness
      change, and c is the camera ID number. This arrangement
      makes it much easier to process all the DVS data together
      in single data files.

Searching around in the jAER commit history for some time, I finally found the class that Gemma made called `MultiDavisCameraChip`. This base class is subclassed for `MultiDAVIS346BCameraChip`.

![multicamerachip](https://github.com/SensorsINI/DHP19/assets/10061874/d8538eee-d06e-4171-80e4-3ad048b6e81f)

Go to the menu _AEChip/Customize AEChip menu_ and add the AEChip for DAVIS346 cameras. When you select this chip, enter 4 when asked for number of cameras.

You should then be able to play these recordings.

Here is a screenshot of playing one of them:

![multicamerachip dhp19](https://github.com/SensorsINI/DHP19/assets/10061874/0a2e656a-55ba-423e-a467-fb2003ce8c7f)

Here is a [YouTube video playing one DHP19 recording](https://youtu.be/v5TBt9atb28)

**Comment by tobidelbruck** [comment]
Updated https://sites.google.com/view/dhp19/jaer to provide this information

**Comment by lsjws2008** [comment]
Thank you very much for your reply. After upgrading jAER to version 2.6.1, I obtained the expected correct results.
