### ISSUE TITLE
how to read .model file

### ISSUE THREAD

**Issue by victkid** [SensorsINI/DHP19#3]
Hi, 

From my understanding, the `DHP_CNN.model` is generated from Keras, but I don't know how to read this file format from Keras. Could you provide some sample testing code for that? Thank you.

**Comment by ShallowWill** [comment]
Hi, have you managed to constructed the 2D heatmaps?  The Heatmaps I got apparently do not match the frames.

**Comment by victkid** [comment]
Mine couldn't match with the frame either. I just used the equation (1) from the paper to get the u and v. I suppose u and v correspond to x and y pixel locations in the frame?  Is there any offset that we should deal with?

For "S1_session1_mov1_7500events" I got something like the following picture. 
![Screenshot from 2019-08-09 15-11-43](https://user-images.githubusercontent.com/2037785/62803295-090b6000-bab8-11e9-8d09-311857196653.png)

**Comment by ShallowWill** [comment]
Author uploaded a file about how to generate 2D heatmaps.

**Comment by enrico-c** [comment]
> Hi,
> 
> From my understanding, the `DHP_CNN.model` is generated from Keras, but I don't know how to read this file format from Keras. Could you provide some sample testing code for that? Thank you.

To load the model:
`model = keras.models.load_model('DHP_CNN.model')`

If you are not familiar with Keras please have a look at the [documentation](https://keras.io/getting-started/faq/)

**Comment by victkid** [comment]
Hi enrico-c,

Thank you for your reply. I'm using the code you provided to load the `.model` file. But I got the following error
`ValueError: Unknown loss function:mse2D`
Is `mse2D` a customized function defined in your network?

**Comment by Adamink** [comment]
> Hi enrico-c,
> 
> Thank you for your reply. I'm using the code you provided to load the `.model` file. But I got the following error
> `ValueError: Unknown loss function:mse2D`
> Is `mse2D` a customized function defined in your network?

When running `model = keras.models.load_model('DHP_CNN.model')`, I have encountered the same question, and I post the traceback information here.

Keras version: 2.2.4
Backend Tensorflow version: 1.14.0
Python version: 3.6.8


```txt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wuxiao/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/wuxiao/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 312, in _deserialize_model
    sample_weight_mode=sample_weight_mode)
  File "/home/wuxiao/.local/lib/python3.6/site-packages/keras/engine/training.py", line 139, in compile
    loss_function = losses.get(loss)
  File "/home/wuxiao/.local/lib/python3.6/site-packages/keras/losses.py", line 133, in get
    return deserialize(identifier)
  File "/home/wuxiao/.local/lib/python3.6/site-packages/keras/losses.py", line 114, in deserialize
    printable_module_name='loss function')
  File "/home/wuxiao/.local/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 165, in deserialize_keras_object
    ':' + function_name)
ValueError: Unknown loss function:mse2D
```

**Comment by victkid** [comment]
> > Hi enrico-c,
> > Thank you for your reply. I'm using the code you provided to load the `.model` file. But I got the following error
> > `ValueError: Unknown loss function:mse2D`
> > Is `mse2D` a customized function defined in your network?
> 
> When running `model = keras.models.load_model('DHP_CNN.model')`, I have encountered the same question, and I post the traceback information here.
> 
> Keras version: 2.2.4
> Backend Tensorflow version: 1.14.0
> Python version: 3.6.8
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/wuxiao/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
>     model = _deserialize_model(f, custom_objects, compile)
>   File "/home/wuxiao/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 312, in _deserialize_model
>     sample_weight_mode=sample_weight_mode)
>   File "/home/wuxiao/.local/lib/python3.6/site-packages/keras/engine/training.py", line 139, in compile
>     loss_function = losses.get(loss)
>   File "/home/wuxiao/.local/lib/python3.6/site-packages/keras/losses.py", line 133, in get
>     return deserialize(identifier)
>   File "/home/wuxiao/.local/lib/python3.6/site-packages/keras/losses.py", line 114, in deserialize
>     printable_module_name='loss function')
>   File "/home/wuxiao/.local/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 165, in deserialize_keras_object
>     ':' + function_name)
> ValueError: Unknown loss function:mse2D
> ```

Have you figured out how to load the model?

**Comment by victkid** [comment]
> > Hi,
> > From my understanding, the `DHP_CNN.model` is generated from Keras, but I don't know how to read this file format from Keras. Could you provide some sample testing code for that? Thank you.
> 
> To load the model:
> `model = keras.models.load_model('DHP_CNN.model')`
> 
> If you are not familiar with Keras please have a look at the [documentation](https://keras.io/getting-started/faq/)

Hi enrico, could you provide some help here?

**Comment by enrico-c** [comment]
The loss function is simply the MSE over the CNN predicted volume. 
The code is  the following (add it to the losses.py file in keras):

```
def mse2D(y_true, y_pred):
    mean_over_ch = K.mean(K.square(y_pred - y_true), axis=-1)
    mean_over_w = K.mean(mean_over_ch, axis=-1)
    mean_over_h = K.mean(mean_over_w, axis=-1)
    return mean_over_h
```
