### ISSUE TITLE
Do APS frames were recorded in the .aedat?

### ISSUE THREAD

**Issue by eleboss** [SensorsINI/DHP19#6]
Dear team,
Thank you very much for providing such a nice dataset.

I am trying to read the APS frames from .aedat, but got nothing. From my understanding, the DAVIS is able to provide APS frames. Do such data contained in this dataset?

Yours.

**Comment by enrico-c** [comment]
Hi @eleboss, thanks for your interest.

> From my understanding, the DAVIS is able to provide APS frames. 

Yes, this is correct.
> Do such data contained in this dataset?

Unfortunately, DHP19 does not include APS frames. From the paper:

> We recorded only the DVS output since the host controller USB bandwidth was insufficient to capture all DVS and APS outputs simultaneously.

**Comment by eleboss** [comment]
Thanks for your quick answer.

It is really a pity that APS frames are not included. 

Anyway, thanks again.

**Comment by tobidelbruck** [comment]
No, frames were not recorded because of the USB bandwidth limitations of 
connecting the 4 cameras to one computer.  I believe this is clear from 
webpage, but if not we will add it.
